# Generated by Django 4.2.7 on 2024-01-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stkapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesaresponse',
            old_name='response_text',
            new_name='response',
        ),
    ]
